package com.solution.smartparkingr.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class SubscriptionPlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String type; // MONTHLY, QUARTERLY, YEARLY
    private Double amount; // Fixed amount for the subscription plan

    // Getters and setters are generated by Lombok's @Data annotation
}
